server.port=8082
spring.application.name=enrichment-correlation-service
spring.datasource.url=jdbc:postgresql://localhost:5432/sdapro
spring.datasource.username=sdapro
spring.datasource.password=sdapro123
spring.jpa.hibernate.ddl-auto=update
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
