server.port=8081
spring.application.name=alert-ingestion-service
spring.datasource.url=jdbc:postgresql://localhost:5432/sdapro
spring.datasource.username=sdapro
spring.datasource.password=sdapro123
spring.jpa.hibernate.ddl-auto=update
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
